version: '3.8'

services:
  postgres_db:
    image: 'postgres:14'
    command: postgres -c 'max_connections=1000'
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - dbdata:/var/lib/postgresql/data

  nestjs:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - DB_TYPE=postgres
      - POSTGRES_HOST=postgres_db
      - POSTGRES_PORT=5432
    ports:
      - '3001:3000' # expose-to-the-world : only-in-the-docker
    depends_on:
      - postgres_db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  dbdata:
